<?php
$reportTitle = $report ? (string)$report['title'] : 'Report unavailable';
$reportType = $report ? ucfirst((string)$report['type']) : 'Report';
$reportStatus = $report ? foreman_status_label((string)$report['status']) : 'Unavailable';
$reportPriorityLabel = $report ? foreman_report_priority_label($report) : 'Unavailable';
$reportPriorityClass = $report ? foreman_report_priority_class($report) : 'report-pill--neutral';
$reportReference = $report ? (string)$report['reference_no'] : 'N/A';
$reportProject = $report ? (string)$report['project_name'] : 'N/A';
$reportDueDate = $report ? foreman_format_date($report['due_date'] ?? null) : 'Not set';
$reportCreatedAt = $report ? foreman_format_datetime($report['created_at'] ?? null) : 'Not recorded';
$reportUpdatedAt = $report ? foreman_format_datetime($report['updated_at'] ?? null) : 'Not recorded';
$reportDetails = $report ? trim((string)($report['details'] ?? '')) : '';
$detailLines = $reportDetails !== '' ? preg_split("/\\r\\n|\\r|\\n/", $reportDetails) : [];
?>
<main class="report-pdf-page">
    <?php if (!$report): ?>
        <section class="report-pdf-card">
            <header class="report-pdf-header">
                <div>
                    <p class="report-pdf-system">Edge Automation</p>
                    <h1>Foreman Report</h1>
                </div>
            </header>
            <section class="report-pdf-section">
                <h2>Report Status</h2>
                <p>Report not found or you do not have access to it.</p>
            </section>
        </section>
    <?php else: ?>
        <section class="report-pdf-card">
            <header class="report-pdf-header">
                <div>
                    <p class="report-pdf-system">Edge Automation</p>
                    <h1>Foreman Report</h1>
                    <p class="report-pdf-subtitle"><?php echo htmlspecialchars($reportType); ?> report document</p>
                </div>
                <div class="report-pdf-generated">
                    <span>Generated by</span>
                    <strong><?php echo htmlspecialchars($foremanProfileName); ?></strong>
                    <span>Generated at <?php echo htmlspecialchars($generatedAt); ?></span>
                </div>
            </header>

            <section class="report-pdf-banner">
                <div>
                    <p class="report-pdf-code"><?php echo htmlspecialchars($reportReference); ?></p>
                    <h2><?php echo htmlspecialchars($reportTitle); ?></h2>
                    <p class="report-pdf-subtitle"><?php echo htmlspecialchars($reportProject); ?></p>
                </div>
                <div class="report-pdf-pill-row">
                    <span class="report-pill <?php echo htmlspecialchars($reportPriorityClass); ?>"><?php echo htmlspecialchars($reportPriorityLabel); ?></span>
                    <span class="report-pill report-pill--neutral"><?php echo htmlspecialchars($reportStatus); ?></span>
                </div>
            </section>

            <section class="report-pdf-section">
                <h2>Report Overview</h2>
                <table class="report-pdf-table">
                    <tbody>
                        <tr>
                            <th>Reference No.</th>
                            <td><?php echo htmlspecialchars($reportReference); ?></td>
                            <th>Report Type</th>
                            <td><?php echo htmlspecialchars($reportType); ?></td>
                        </tr>
                        <tr>
                            <th>Project</th>
                            <td><?php echo htmlspecialchars($reportProject); ?></td>
                            <th>Status</th>
                            <td><?php echo htmlspecialchars($reportStatus); ?></td>
                        </tr>
                        <tr>
                            <th>Priority</th>
                            <td><?php echo htmlspecialchars($reportPriorityLabel); ?></td>
                            <th>Due Date</th>
                            <td><?php echo htmlspecialchars($reportDueDate); ?></td>
                        </tr>
                        <tr>
                            <th>Created At</th>
                            <td><?php echo htmlspecialchars($reportCreatedAt); ?></td>
                            <th>Last Updated</th>
                            <td><?php echo htmlspecialchars($reportUpdatedAt); ?></td>
                        </tr>
                    </tbody>
                </table>
            </section>

            <section class="report-pdf-section">
                <h2>Details</h2>
                <?php if (empty($detailLines)): ?>
                    <p class="report-pdf-copy">No details recorded.</p>
                <?php else: ?>
                    <div class="report-pdf-copy">
                        <?php foreach ($detailLines as $line): ?>
                            <?php $line = trim((string)$line); ?>
                            <?php if ($line === ''): ?>
                                <div class="report-pdf-spacer"></div>
                            <?php else: ?>
                                <p><?php echo htmlspecialchars($line); ?></p>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </section>

            <footer class="report-pdf-footer">
                <div>Generated by: <strong><?php echo htmlspecialchars($foremanProfileName); ?></strong></div>
                <div>Generated at: <strong><?php echo htmlspecialchars($generatedAt); ?></strong></div>
                <div class="report-pdf-page-counter">Page <span class="report-pdf-page-number"></span></div>
            </footer>
        </section>
    <?php endif; ?>
</main>
